name = "magic-kids-chat"
main = "src/index.js"
compatibility_date = "2026-10-03"

[[d1_databases]]
binding = "DB"
database_name = "magic-kids-chat-db"
database_id = "5546268a-d1b2-4ce3-bf91-4a5f1c1e09ec"
